# Scaffolding generated by Casein v5.0.0.0

module Casein
  class TrainersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Trainers'
  		@trainers = Trainer.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View trainer'
      @trainer = Trainer.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new trainer'
    	@trainer = Trainer.new
    end

    def create
      @trainer = Trainer.new trainer_params
    
      if @trainer.save
        flash[:notice] = 'Trainer created'
        redirect_to casein_trainers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new trainer'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update trainer'
      
      @trainer = Trainer.find params[:id]
    
      if @trainer.update_attributes trainer_params
        flash[:notice] = 'Trainer has been updated'
        redirect_to casein_trainers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this trainer'
        render :action => :show
      end
    end
 
    def destroy
      @trainer = Trainer.find params[:id]

      @trainer.destroy
      flash[:notice] = 'Trainer has been deleted'
      redirect_to casein_trainers_path
    end
  
    private
      
      def trainer_params
        params.require(:trainer).permit(:name, :trainer_title, :trainer_particulars)
      end

  end
end